/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as GitSplatRouteImport } from "./routes/git/$";
import { Route as AuthenticatedChatRouteImport } from "./routes/_authenticated/chat";
import { Route as AuthenticatedAccessRouteImport } from "./routes/_authenticated/access";
import { Route as authSignInRouteImport } from "./routes/(auth)/sign-in";
import { Route as AuthenticatedStorageIndexRouteImport } from "./routes/_authenticated/storage/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as AuthenticatedStorageNewRouteImport } from "./routes/_authenticated/storage/new";
import { Route as AuthenticatedStorageRepoNameRouteImport } from "./routes/_authenticated/storage/$repoName";

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const GitSplatRoute = GitSplatRouteImport.update({
  id: "/git/$",
  path: "/git/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedAccessRoute = AuthenticatedAccessRouteImport.update({
  id: "/access",
  path: "/access",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const authSignInRoute = authSignInRouteImport.update({
  id: "/(auth)/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedStorageIndexRoute =
  AuthenticatedStorageIndexRouteImport.update({
    id: "/storage/",
    path: "/storage/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedStorageNewRoute = AuthenticatedStorageNewRouteImport.update({
  id: "/storage/new",
  path: "/storage/new",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedStorageRepoNameRoute =
  AuthenticatedStorageRepoNameRouteImport.update({
    id: "/storage/$repoName",
    path: "/storage/$repoName",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/sign-in": typeof authSignInRoute;
  "/access": typeof AuthenticatedAccessRoute;
  "/chat": typeof AuthenticatedChatRoute;
  "/git/$": typeof GitSplatRoute;
  "/storage/$repoName": typeof AuthenticatedStorageRepoNameRoute;
  "/storage/new": typeof AuthenticatedStorageNewRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/storage/": typeof AuthenticatedStorageIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/sign-in": typeof authSignInRoute;
  "/access": typeof AuthenticatedAccessRoute;
  "/chat": typeof AuthenticatedChatRoute;
  "/git/$": typeof GitSplatRoute;
  "/storage/$repoName": typeof AuthenticatedStorageRepoNameRoute;
  "/storage/new": typeof AuthenticatedStorageNewRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/storage": typeof AuthenticatedStorageIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren;
  "/(auth)/sign-in": typeof authSignInRoute;
  "/_authenticated/access": typeof AuthenticatedAccessRoute;
  "/_authenticated/chat": typeof AuthenticatedChatRoute;
  "/git/$": typeof GitSplatRoute;
  "/_authenticated/storage/$repoName": typeof AuthenticatedStorageRepoNameRoute;
  "/_authenticated/storage/new": typeof AuthenticatedStorageNewRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/_authenticated/storage/": typeof AuthenticatedStorageIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/sign-in"
    | "/access"
    | "/chat"
    | "/git/$"
    | "/storage/$repoName"
    | "/storage/new"
    | "/api/auth/$"
    | "/storage/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/sign-in"
    | "/access"
    | "/chat"
    | "/git/$"
    | "/storage/$repoName"
    | "/storage/new"
    | "/api/auth/$"
    | "/storage";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/(auth)/sign-in"
    | "/_authenticated/access"
    | "/_authenticated/chat"
    | "/git/$"
    | "/_authenticated/storage/$repoName"
    | "/_authenticated/storage/new"
    | "/api/auth/$"
    | "/_authenticated/storage/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  authSignInRoute: typeof authSignInRoute;
  GitSplatRoute: typeof GitSplatRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/git/$": {
      id: "/git/$";
      path: "/git/$";
      fullPath: "/git/$";
      preLoaderRoute: typeof GitSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/chat": {
      id: "/_authenticated/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof AuthenticatedChatRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/access": {
      id: "/_authenticated/access";
      path: "/access";
      fullPath: "/access";
      preLoaderRoute: typeof AuthenticatedAccessRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/(auth)/sign-in": {
      id: "/(auth)/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof authSignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/storage/": {
      id: "/_authenticated/storage/";
      path: "/storage";
      fullPath: "/storage/";
      preLoaderRoute: typeof AuthenticatedStorageIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/storage/new": {
      id: "/_authenticated/storage/new";
      path: "/storage/new";
      fullPath: "/storage/new";
      preLoaderRoute: typeof AuthenticatedStorageNewRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/storage/$repoName": {
      id: "/_authenticated/storage/$repoName";
      path: "/storage/$repoName";
      fullPath: "/storage/$repoName";
      preLoaderRoute: typeof AuthenticatedStorageRepoNameRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessRoute: typeof AuthenticatedAccessRoute;
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute;
  AuthenticatedStorageRepoNameRoute: typeof AuthenticatedStorageRepoNameRoute;
  AuthenticatedStorageNewRoute: typeof AuthenticatedStorageNewRoute;
  AuthenticatedStorageIndexRoute: typeof AuthenticatedStorageIndexRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessRoute: AuthenticatedAccessRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedStorageRepoNameRoute: AuthenticatedStorageRepoNameRoute,
  AuthenticatedStorageNewRoute: AuthenticatedStorageNewRoute,
  AuthenticatedStorageIndexRoute: AuthenticatedStorageIndexRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  GitSplatRoute: GitSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.ts";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
