/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as GitSplatRouteImport } from "./routes/git/$";
import { Route as AuthenticatedChatRouteImport } from "./routes/_authenticated/chat";
import { Route as AuthenticatedAccessRouteImport } from "./routes/_authenticated/access";
import { Route as authSignInRouteImport } from "./routes/(auth)/sign-in";
import { Route as AuthenticatedStorageIndexRouteImport } from "./routes/_authenticated/storage/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as AuthenticatedStorageNewRouteImport } from "./routes/_authenticated/storage/new";
import { Route as AuthenticatedStorageRepoNameRouteRouteImport } from "./routes/_authenticated/storage/$repoName/route";
import { Route as AuthenticatedStorageRepoNameIndexRouteImport } from "./routes/_authenticated/storage/$repoName/index";
import { Route as AuthenticatedStorageRepoNameSettingsRouteImport } from "./routes/_authenticated/storage/$repoName/settings";
import { Route as AuthenticatedStorageRepoNameChangesRouteImport } from "./routes/_authenticated/storage/$repoName/changes";

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const GitSplatRoute = GitSplatRouteImport.update({
  id: "/git/$",
  path: "/git/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedAccessRoute = AuthenticatedAccessRouteImport.update({
  id: "/access",
  path: "/access",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const authSignInRoute = authSignInRouteImport.update({
  id: "/(auth)/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedStorageIndexRoute =
  AuthenticatedStorageIndexRouteImport.update({
    id: "/storage/",
    path: "/storage/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedStorageNewRoute = AuthenticatedStorageNewRouteImport.update({
  id: "/storage/new",
  path: "/storage/new",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedStorageRepoNameRouteRoute =
  AuthenticatedStorageRepoNameRouteRouteImport.update({
    id: "/storage/$repoName",
    path: "/storage/$repoName",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedStorageRepoNameIndexRoute =
  AuthenticatedStorageRepoNameIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedStorageRepoNameRouteRoute,
  } as any);
const AuthenticatedStorageRepoNameSettingsRoute =
  AuthenticatedStorageRepoNameSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => AuthenticatedStorageRepoNameRouteRoute,
  } as any);
const AuthenticatedStorageRepoNameChangesRoute =
  AuthenticatedStorageRepoNameChangesRouteImport.update({
    id: "/changes",
    path: "/changes",
    getParentRoute: () => AuthenticatedStorageRepoNameRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/sign-in": typeof authSignInRoute;
  "/access": typeof AuthenticatedAccessRoute;
  "/chat": typeof AuthenticatedChatRoute;
  "/git/$": typeof GitSplatRoute;
  "/storage/$repoName": typeof AuthenticatedStorageRepoNameRouteRouteWithChildren;
  "/storage/new": typeof AuthenticatedStorageNewRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/storage/": typeof AuthenticatedStorageIndexRoute;
  "/storage/$repoName/changes": typeof AuthenticatedStorageRepoNameChangesRoute;
  "/storage/$repoName/settings": typeof AuthenticatedStorageRepoNameSettingsRoute;
  "/storage/$repoName/": typeof AuthenticatedStorageRepoNameIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/sign-in": typeof authSignInRoute;
  "/access": typeof AuthenticatedAccessRoute;
  "/chat": typeof AuthenticatedChatRoute;
  "/git/$": typeof GitSplatRoute;
  "/storage/new": typeof AuthenticatedStorageNewRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/storage": typeof AuthenticatedStorageIndexRoute;
  "/storage/$repoName/changes": typeof AuthenticatedStorageRepoNameChangesRoute;
  "/storage/$repoName/settings": typeof AuthenticatedStorageRepoNameSettingsRoute;
  "/storage/$repoName": typeof AuthenticatedStorageRepoNameIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren;
  "/(auth)/sign-in": typeof authSignInRoute;
  "/_authenticated/access": typeof AuthenticatedAccessRoute;
  "/_authenticated/chat": typeof AuthenticatedChatRoute;
  "/git/$": typeof GitSplatRoute;
  "/_authenticated/storage/$repoName": typeof AuthenticatedStorageRepoNameRouteRouteWithChildren;
  "/_authenticated/storage/new": typeof AuthenticatedStorageNewRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/_authenticated/storage/": typeof AuthenticatedStorageIndexRoute;
  "/_authenticated/storage/$repoName/changes": typeof AuthenticatedStorageRepoNameChangesRoute;
  "/_authenticated/storage/$repoName/settings": typeof AuthenticatedStorageRepoNameSettingsRoute;
  "/_authenticated/storage/$repoName/": typeof AuthenticatedStorageRepoNameIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/sign-in"
    | "/access"
    | "/chat"
    | "/git/$"
    | "/storage/$repoName"
    | "/storage/new"
    | "/api/auth/$"
    | "/storage/"
    | "/storage/$repoName/changes"
    | "/storage/$repoName/settings"
    | "/storage/$repoName/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/sign-in"
    | "/access"
    | "/chat"
    | "/git/$"
    | "/storage/new"
    | "/api/auth/$"
    | "/storage"
    | "/storage/$repoName/changes"
    | "/storage/$repoName/settings"
    | "/storage/$repoName";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/(auth)/sign-in"
    | "/_authenticated/access"
    | "/_authenticated/chat"
    | "/git/$"
    | "/_authenticated/storage/$repoName"
    | "/_authenticated/storage/new"
    | "/api/auth/$"
    | "/_authenticated/storage/"
    | "/_authenticated/storage/$repoName/changes"
    | "/_authenticated/storage/$repoName/settings"
    | "/_authenticated/storage/$repoName/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  authSignInRoute: typeof authSignInRoute;
  GitSplatRoute: typeof GitSplatRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/git/$": {
      id: "/git/$";
      path: "/git/$";
      fullPath: "/git/$";
      preLoaderRoute: typeof GitSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/chat": {
      id: "/_authenticated/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof AuthenticatedChatRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/access": {
      id: "/_authenticated/access";
      path: "/access";
      fullPath: "/access";
      preLoaderRoute: typeof AuthenticatedAccessRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/(auth)/sign-in": {
      id: "/(auth)/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof authSignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/storage/": {
      id: "/_authenticated/storage/";
      path: "/storage";
      fullPath: "/storage/";
      preLoaderRoute: typeof AuthenticatedStorageIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/storage/new": {
      id: "/_authenticated/storage/new";
      path: "/storage/new";
      fullPath: "/storage/new";
      preLoaderRoute: typeof AuthenticatedStorageNewRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/storage/$repoName": {
      id: "/_authenticated/storage/$repoName";
      path: "/storage/$repoName";
      fullPath: "/storage/$repoName";
      preLoaderRoute: typeof AuthenticatedStorageRepoNameRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/storage/$repoName/": {
      id: "/_authenticated/storage/$repoName/";
      path: "/";
      fullPath: "/storage/$repoName/";
      preLoaderRoute: typeof AuthenticatedStorageRepoNameIndexRouteImport;
      parentRoute: typeof AuthenticatedStorageRepoNameRouteRoute;
    };
    "/_authenticated/storage/$repoName/settings": {
      id: "/_authenticated/storage/$repoName/settings";
      path: "/settings";
      fullPath: "/storage/$repoName/settings";
      preLoaderRoute: typeof AuthenticatedStorageRepoNameSettingsRouteImport;
      parentRoute: typeof AuthenticatedStorageRepoNameRouteRoute;
    };
    "/_authenticated/storage/$repoName/changes": {
      id: "/_authenticated/storage/$repoName/changes";
      path: "/changes";
      fullPath: "/storage/$repoName/changes";
      preLoaderRoute: typeof AuthenticatedStorageRepoNameChangesRouteImport;
      parentRoute: typeof AuthenticatedStorageRepoNameRouteRoute;
    };
  }
}

interface AuthenticatedStorageRepoNameRouteRouteChildren {
  AuthenticatedStorageRepoNameChangesRoute: typeof AuthenticatedStorageRepoNameChangesRoute;
  AuthenticatedStorageRepoNameSettingsRoute: typeof AuthenticatedStorageRepoNameSettingsRoute;
  AuthenticatedStorageRepoNameIndexRoute: typeof AuthenticatedStorageRepoNameIndexRoute;
}

const AuthenticatedStorageRepoNameRouteRouteChildren: AuthenticatedStorageRepoNameRouteRouteChildren =
  {
    AuthenticatedStorageRepoNameChangesRoute:
      AuthenticatedStorageRepoNameChangesRoute,
    AuthenticatedStorageRepoNameSettingsRoute:
      AuthenticatedStorageRepoNameSettingsRoute,
    AuthenticatedStorageRepoNameIndexRoute:
      AuthenticatedStorageRepoNameIndexRoute,
  };

const AuthenticatedStorageRepoNameRouteRouteWithChildren =
  AuthenticatedStorageRepoNameRouteRoute._addFileChildren(
    AuthenticatedStorageRepoNameRouteRouteChildren,
  );

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessRoute: typeof AuthenticatedAccessRoute;
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute;
  AuthenticatedStorageRepoNameRouteRoute: typeof AuthenticatedStorageRepoNameRouteRouteWithChildren;
  AuthenticatedStorageNewRoute: typeof AuthenticatedStorageNewRoute;
  AuthenticatedStorageIndexRoute: typeof AuthenticatedStorageIndexRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessRoute: AuthenticatedAccessRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedStorageRepoNameRouteRoute:
    AuthenticatedStorageRepoNameRouteRouteWithChildren,
  AuthenticatedStorageNewRoute: AuthenticatedStorageNewRoute,
  AuthenticatedStorageIndexRoute: AuthenticatedStorageIndexRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  GitSplatRoute: GitSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.ts";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
